// <auto-generated />
using System;
using Genesis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Genesis.Data.Migrations
{
    [DbContext(typeof(GenesisContext))]
    partial class GenesisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Genesis.Core.Domaine.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EntrepriseId");

                    b.Property<string>("Pays");

                    b.Property<string>("Rue");

                    b.Property<string>("Ville");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Adresse");
                });

            modelBuilder.Entity("Genesis.Core.Domaine.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresseId");

                    b.Property<int>("TypeContact");

                    b.Property<string>("VATNumber");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Genesis.Core.Domaine.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContactId");

                    b.Property<string>("SiegeSocial");

                    b.Property<string>("VatNumberEnt");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("Genesis.Core.Domaine.Adresse", b =>
                {
                    b.HasOne("Genesis.Core.Domaine.Entreprise")
                        .WithMany("Adresses")
                        .HasForeignKey("EntrepriseId");
                });

            modelBuilder.Entity("Genesis.Core.Domaine.Contact", b =>
                {
                    b.HasOne("Genesis.Core.Domaine.Adresse", "Adresse")
                        .WithMany()
                        .HasForeignKey("AdresseId");
                });

            modelBuilder.Entity("Genesis.Core.Domaine.Entreprise", b =>
                {
                    b.HasOne("Genesis.Core.Domaine.Contact")
                        .WithMany("Entreprises")
                        .HasForeignKey("ContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
